worker_processes 1;
error_log /dev/stderr warn;
pid /var/run/nginx.pid;

events {
    worker_connections 64;
}

http {
    access_log off;
    default_type application/json;

    server {
        listen __PORT__;
        root /data/results;

        location / {
            autoindex on;
            autoindex_format json;
            add_header Access-Control-Allow-Origin "*";
            add_header Cache-Control "no-cache, no-store";
        }
    }
}
