name: "Fritz!Box Call Monitor to MQTT"
description: "Sends call monitor messages from a Fritz!Box to an MQTT broker"
version: "1.2.0"
slug: "fritz-callmonitor2mqtt"
init: false
arch:
  # - aarch64
  - amd64
  # - armhf
  # - armv7
  # - i386
url: "https://github.com/akentner/homeassistant-addons"
startup: "application"
boot: "auto"
host_network: false
map:
  - "config:rw"
  - "ssl"

options:
  # FritzBox
  fritzbox_host: "fritz.box"
  fritzbox_port: 1012

  # PBX
  pbx_country_code: "49"
  pbx_local_area_code: ""
  pbx_msns: []
  pbx_extensions: []

  # MQTT
  mqtt_broker: "core-mosquitto"
  mqtt_port: 1883
  mqtt_username: "mosquitto"
  mqtt_password: "mosquitto"
  mqtt_client_id: "fritz-callmonitor2mqtt"
  mqtt_topic_prefix: "fritz/callmonitor"
  mqtt_qos: 1
  mqtt_retain: true
  mqtt_keep_alive: 60
  mqtt_connect_timeout: 30

  # App
  app_log_level: "info"
  app_call_history_size: 50
  app_reconnect_delay: 10
  app_health_check_port: 8080
  app_timezone: "Europe/Berlin"

  # Database
  database_data_dir: "/data"


schema:
  fritzbox_host: "str"
  fritzbox_port: "int"
  pbx_country_code: "str"
  pbx_local_area_code: "str"
  pbx_msns:
    - "str"
  pbx_extensions:
    - number: "str"
      name: "str"
      type: list(VOICEBOX|DECT|VOIP)?
  mqtt_broker: "str"
  mqtt_port: "int"
  mqtt_username: "str"
  mqtt_password: "str"
  mqtt_client_id: "str"
  mqtt_topic_prefix: "str"
  mqtt_qos: "int"
  mqtt_retain: "bool"
  mqtt_keep_alive: "int"
  mqtt_connect_timeout: "int"
  app_log_level: list(debug|info|warning|error|critical)
  app_call_history_size: "int"
  app_reconnect_delay: "int"
  app_health_check_port: "int"
  app_timezone: "str"
  database_data_dir: "str"
