name: Build Phone Logger

on:
  push:
    branches:
      - main
    paths:
      - "phone-logger/**"
    tags:
      - "phone-logger/v*"
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/_build-template.yml
    with:
      addon-name: phone-logger
      addon-display-name: "Phone Logger"
      addon-description: "Phone logging and adapter integration for Home Assistant"
      archs: '["amd64"]'
